name: gh_issue_tracker
description: "Github Issue Tracker for GTAF"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  flutter_native_splash: ^2.4.1
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
